[[KNITRO]]
git-tree-sha1 = "3bcf8391cf37bf1c6656f847149a7bd066e1096f"
arch = "x86_64"
os = "linux"

    [[KNITRO.download]]
    sha256 = "bdfa52525815148849554f6ab8debd33f0a76c6c6d6c443029f3d1ffb809aecc"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v16.0.0-binary/x86_64-linux-gnu.tar.bz2"
[[KNITRO]]
git-tree-sha1 = "794de8e39303d92a33bec6ae1a29415e6bcefddd"
arch = "aarch64"
os = "linux"

    [[KNITRO.download]]
    sha256 = "b26fc27796473f3a4de0f6e1867133a1cb48ed2e3018c7f0f62a61248ca3ece1"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v16.0.0-binary/aarch64-linux-gnu.tar.bz2"
[[KNITRO]]
git-tree-sha1 = "1212bd761722e4fbd6f23765d2ff2da965f510bf"
arch = "aarch64"
os = "macos"

    [[KNITRO.download]]
    sha256 = "a045439ffa502ab81bac2e3be36ae972fa5bdb0667b2a7850ffccd6628598515"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v16.0.0-binary/aarch64-apple-darwin.tar.bz2"
[[KNITRO]]
git-tree-sha1 = "a8d92bf108f10a5656249786d8d2f2aa05c5c164"
arch = "x86_64"
os = "windows"

    [[KNITRO.download]]
    sha256 = "420fa33aceab47ef926eb09bcb3a82aae42da28226d4e3c8dfbfc8a809f58d04"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v16.0.0-binary/x86_64-w64-mingw32.tar.bz2"
